### PR TITLE
Render title as textarea field

### PR DESCRIPTION
**Pull request by aucuparia**
This change makes very long titles to be displayed in multiple lines so that the full title is visible

### CODE REVIEW

**Review by lwesterhof — CHANGES_REQUESTED** [review]
Why can't we handle this in de UI schemas?

**Comment by aucuparia** [comment]
> Why can't we handle this in de UI schemas?

I considered it, but that would allow for newlines to be (inadvertently) added to the title, which would mess things up downstream (e.g. the title is used in the Subject fields of emails and in their contents). We could add input sanitation to the field to prevent this from happening, but a textarea input field also suggests to the researcher that a multiline title would be permissible. So then we would also have to add a note or good error messaging to indicate that the title is supposed to be a single string. This solution requires no sanitizing and keeps things clear for the researcher, while having the desired effect (i.e. non-truncated display of long titles).

**Comment by aucuparia** [comment]
Thought about it a bit more: a more elegant solution is to separate the datarequest uiSchema into two uiSchemas: one for rendering the datarequest submission form, and one for rendering a read-only version (i.e. everywhere other than the submission form).

WIP because of issues with compiling the Javascript.

**Review by lwesterhof — APPROVED** [review]
LGTM

**Pull request merged**
